[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_ckapple = "3CLbFjWR9UGNFFcUCkyNqWmTpk2vkYCTk17RxMEyyhZd"

[registry]
url = "https://black-side-dawn.solana-devnet.quiknode.pro/34914fab50708164e45c152a3bb6135d85ae7611"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
